"""Agrego start_date a Tour

Revision ID: 9583565aa0cc
Revises: 
Create Date: 2025-08-20 19:35:31.075023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9583565aa0cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_id', sa.Integer(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_tour_destination', 'destination', ['destination_id'], ['id'])
        batch_op.drop_column('end_date')
        batch_op.drop_column('destination')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=False))
        batch_op.drop_constraint('fk_tour_destination', type_='foreignkey')
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('destination_id')

    # ### end Alembic commands ###
